manifest:
  remotes:
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: tklzg
      url-base: https://github.com/tklzg
  projects:
    - name: zmk-petejohanson
      remote: tklzg
      revision: feat/pointers-move-scroll
    - name: zmk-pmw3610-driver-badjeff
      remote: tklzg
      revision: main
    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main
    - name: zmk-input-behavior-listener
      remote: tklzg
      revision: main
  self:
    path: config